### ISSUE TITLE
Links and Code look the same

### ISSUE THREAD

**Issue by evans** [meteor/meteor-theme-hexo#63]
Code used to have a background color to differentiate it 😢 

@abernix might have some idea?

**Comment by abernix** [comment]
Just to clarify, the issue is affecting in-line code blocks, not regular code blocks. (I realize it might seem obvious, but screenshots are tremendously helpful for demonstrating these sorts of nuances.).

![image](https://user-images.githubusercontent.com/841294/38602867-af4c276e-3d74-11e8-87b2-c1fcae323d69.png)

Thanks for filing this!
